import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '../layout/Layout';
import MainCarousel from '@/layout/HomePage/MainCarousel';
import DivOne from '@/layout/HomePage/DivOne';
import WhyChooseUs from '@/layout/HomePage/WhyChooseUs';
import OurApartments from '@/layout/HomePage/OurApartments';
import InteractiveMap from '@/layout/HomePage/InteractiveMap';
import CustomerSay from '@/layout/HomePage/CustomerSay';
import Activity from '@/layout/HomePage/Actitvity';
import Partner from '@/layout/HomePage/Partner';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout> 
        <MainCarousel />
        <DivOne />
        <WhyChooseUs />
        <OurApartments />
        <InteractiveMap />
        <CustomerSay />
        <Activity />
        <Partner />
      </Layout>
    </>
  )
}

import React from 'react';
import { Button, Space } from 'antd';

const App: React.FC = () => (
  <Space wrap>
    <Button type="primary">Primary Button</Button>
    <Button>Default Button</Button>
    <Button type="dashed">Dashed Button</Button>
    <Button type="text">Text Button</Button>
    <Button type="link">Link Button</Button>
  </Space>
);
